spring:
  application:
    name: CardsMS
  datasource:
    url: jdbc:mysql://localhost:3306/cards
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true